/** @format */

import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { GlobalStyle } from "./global.style";
import { Theme } from "./styles/theme";
import { AppWrapper } from "./context";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Sanaz TaskList",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <Theme>
        <GlobalStyle />
        <body className={inter.className}>
          <AppWrapper>{children}</AppWrapper>
        </body>
      </Theme>
    </html>
  );
}
